[package]
name = "stdf-record-derive"
version = "0.1.1"
authors = ["Casey Marshall <git@cmars.tech>"]
description = "Procedural macros supporting the `stdf` crate"
license = "Apache-2.0"

[dependencies]
syn = "0.15.21"
quote = "0.6.10"
proc-macro2 = "0.4.24"

[lib]
proc-macro = true
